[project]
name = "my-test-package"
version= "0.1.0"
description = "Test"
readme = "README.md"
keywords = ["netCDF", "UM", "postprocessing"]
requires-python = ">=3.10"
dependencies = [
    "numpy <2",
    "scitools-iris >=3.11.1",
]

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=80", 
    "setuptools-scm[simple]>=8",
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false