name: Setup SSH
description: Action to setup SSH connection at the job level
inputs:
  hosts:
    required: true
    description: |
      Space- or newline-separated list of SSH hosts to add to the SSH config. Each entry can optionally
      include an alias using the format `host:alias` (e.g. `myhost.org.au:myalias`), allowing
      connection with `ssh user@myalias` instead of `ssh user@myhost.org.au`.
  private-key:
    required: true
    description: Private key as a string
  user:
    required: false
    description: |
      Default user for SSH connections. When provided, it is added to the SSH config to allow
      connection with `ssh myhost.org.au` instead of `ssh user@myhost.org.au`.
  private-key-name:
    required: false
    description: name of ephemeral generated private key file
    default: 'priv.key'
  private-key-passphrase:
    required: false
    description: Passphrase for the private key
outputs:
  private-key-path:
    value: ${{ steps.pk.outputs.path }}
    description: Path to the generated private key file
runs:
  using: "composite"
  steps:
    - name: Sanity check on hosts input
      shell: bash
      env:
        HOSTS: ${{ inputs.hosts }}
      run: |
        for host in "$HOSTS"; do
          if ! [[ "$host" =~ ^[^:]+(:[^:]+)?$ ]]; then
            echo "::error::Invalid host entry '$host'. Each entry in 'hosts' must be in the format 'hostname' or 'hostname:alias'."
            exit 1
          fi
        done
    - name: Add ~/.ssh directory
      shell: bash
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
    - name: Add private key
      shell: bash
      id: pk
      env:
        KEY: ${{ inputs.private-key }}
        KEY_NAME: ${{ inputs.private-key-name }}
      run: |
        path="$HOME/.ssh/$KEY_NAME"
        echo "$KEY" > "$path"
        chmod 600 "$path"
        echo "path=$path" >> $GITHUB_OUTPUT
    - name: Check passphrase
      shell: bash
      env:
        PASSPHRASE: "${{ inputs.private-key-passphrase }}"
        KEY_PATH: "${{ steps.pk.outputs.path }}"
      run: |
        # Try to decrypt the private key with the provided passphrase (if any)
        if ! ssh-keygen -y -P "$PASSPHRASE" -f "$KEY_PATH" > /dev/null; then
          # If the decryption fail, it means that either the private key is passphrase-protected
          # but no passphrase was provided, or the provided passphrase is incorrect
          if [[ -z "$PASSPHRASE" ]]; then
            msg="The provided 'private-key' is passphrase-protected, but no 'private-key-passphrase' was provided."
          else
            msg="The provided 'private-key-passphrase' is incorrect for the provided 'private-key'."
          fi
          echo "::error::$msg"
          exit 1
        fi
    # For security reasons, ssh-add doesn't allow to pass the passphrase from stdin,
    # therefore we must use expect (https://gist.github.com/matthiasbalke/f0abe1e6c18704f086389009075c645e)
    - name: Add passphrase to ssh-agent
      if: inputs.private-key-passphrase != ''
      shell: bash
      env:
        PASSPHRASE: ${{ inputs.private-key-passphrase }}
        KEY_PATH: ${{ steps.pk.outputs.path }}
      run: |
        # Download and install expect
        sudo apt-get install -y expect
        # Start ssh-agent and add the private key with the passphrase
        eval "$(ssh-agent -s)"
        expect -c "
          spawn ssh-add \"$KEY_PATH\"
          expect \"Enter passphrase for *\"
          send \"${PASSPHRASE}\r\"
          expect \"Identity added: *\"
        "
        # Export SSH_AUTH_SOCK and SSH_AGENT_PID to the environment so subsequent steps
        # in the job using this action can use the same ssh-agent
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
        echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
    # In the ssh config we set for each host:
    # StrictHostKeyChecking accept-new - To automatically accept new host keys
    # IdentityFile <path> - The private ssh key to be used
    # ConnectTimeout 60 - Avoid hanging indefinitely if the server is unreachable.
    # ServerAliveInterval 60 - Send a "probe" every minute to verify that the connection is
    #                          still active. Avoid keeping stale connections
    # ServerAliveCountMax 3 - After 3 failed "probes", the connection will be closed.
    # User <user> - User only if the user input is provided
    - name: Add hosts to ssh config
      env:
        HOSTS: ${{ inputs.hosts }}
        USER: ${{ inputs.user }}
      shell: bash
      run: |
        hosts=$(echo "$HOSTS" | tr '\n' ' ' | xargs)
        for host in $hosts; do
          # Split the host by colon to separate the hostname from the alias (if any)
          # If no alias is provided, the hostname and alias will be the same, which
          # would still work fine
          hostname=$(echo "$host" | cut -d: -f1)
          alias=$(echo "$host" | cut -d: -f2)
          cat >> ~/.ssh/config <<EOF
        Host $alias
          Hostname $hostname
          StrictHostKeyChecking accept-new
          IdentityFile ${{ steps.pk.outputs.path }}
          ConnectTimeout 60
          ServerAliveInterval 60
          ServerAliveCountMax 3
          ${USER:+User $USER}
        EOF
        done